name: "Event pipeline"

on:
    push: #event whenever a push is made in github
        branches:
            main
    pull_request:
        branches:
            main

jobs:
    on-push: #name of the job
        runs-on: ubuntu-latest
        steps:
            - name: "running on main push"
              run: echo "Running on main push"
<<<<<<< HEAD
                none
=======

>>>>>>> 9b3cf8b0dc961e9173bad14bdffc53317dc1dfdf
    on-pull-request:
        runs-on: ubutu-latest
        steps:
            - name: "running pull in github"
              run: echo "running pull in github"




